version: "3.7"

volumes:
    mariadb-data:
    redis-data:

services:
    web:
        image: ceskakrutacz
        build: .
        restart: unless-stopped
        tty: true
        volumes:
            - .:/app
            - .docker/on-startup.sh:/docker-entrypoint.d/on-startup.sh
        depends_on:
            - mariadb
        ports:
            - "8080:8080"
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            XDEBUG_MODE: debug
            PHP_IDE_CONFIG: "serverName=ceskakruta"

    mariadb:
        image: mariadb:10.1
        restart: unless-stopped
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "ceskakruta"
        volumes:
          - mariadb-data:/var/lib/mysql
        ports:
          - 3306:3306

    js-watch:
        image: ceskakrutacz
        volumes:
            - .:/app
        restart: unless-stopped
        entrypoint: [""]
        command: ["bash", "-c", "npm install && npm run watch"]
        tty: true

    adminer:
        image: adminer:4.8.0
        ports:
            - "8000:8080"
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
        depends_on:
            - mariadb
