# https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

name: Release

permissions:
  deployments: write
  packages: write

on:
    workflow_run:
        workflows: [Tests]
        types:
            - completed
        branches:
            - main

jobs:
    deploy:
        name: "FTP deploy"
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none # default is xdebug
                    extensions: mbstring, uuid # needed by phpunit

            -   run: composer install --no-progress
            -   run: npm install
            -   run: npm run build

            -   name: 📂 Upload files
                uses: SamKirkland/FTP-Deploy-Action@v4.3.5
                with:
                    server: ${{ secrets.FTP_SERVER }}
                    username: ${{ secrets.FTP_USERNAME }}
                    password: ${{ secrets.FTP_PASSWORD }}
                    server-dir: "./web/"
                    exclude: |
                        **/.git*
                        **/.git*/**
                        **/node_modules/**
                        **/vendor/**
                        **/.docker/**
                        **/.github/**
                        **/assets/**
                        **/var/**
                        .env.local

            -   name: Clear cache
                uses: joutvhu/ftp-transfer@v1
                with:
                    host: ${{ secrets.FTP_SERVER }}
                    username: ${{ secrets.FTP_USERNAME }}
                    password: ${{ secrets.FTP_PASSWORD }}
                    commands: |
                        rename ./web/var/cache/prod ./web/var/cache/prod_old
                        rmdir ./web/var/cache/prod_old
